let report=null;
const $=id=>document.getElementById(id);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function validate(value){if(!value||value.schemaVersion!==1||!Array.isArray(value.devices)||value.devices.length>20000)throw Error('Expected a DriverLens schemaVersion 1 report with a devices array.');for(const d of value.devices){if(!d||typeof d.name!=='string'||typeof d.id!=='string'||!['review','observed'].includes(d.status))throw Error('Report contains an invalid device record.');}return value;}
function filtered(){if(!report)return[];const q=$('search').value.toLowerCase();return report.devices.filter(d=>(!q||[d.name,d.provider,d.version,d.inf,d.vid,d.pid,d.deviceClass].join(' ').toLowerCase().includes(q))&&($('status').value==='all'||d.status===$('status').value)&&($('architecture').value==='all'||d.architecture===$('architecture').value)&&($('bus').value==='all'||d.bus===$('bus').value));}
function render(){if(!report)return;const list=filtered();$('total').textContent=report.devices.length;$('review').textContent=report.devices.filter(d=>d.status==='review').length;$('known').textContent=report.devices.filter(d=>['ARM64','x64','x86','ARM64EC','ARM64X','ARM32'].includes(d.architecture)).length;$('system').textContent=report.system?.architecture||'Unknown';$('count').textContent=`${list.length} of ${report.devices.length} devices · ${report.system?.os||'Unknown OS'} · ${report.sample?'Sample data':'Local inventory'} · ${report.generatedAt||'Date unknown'}`;
$('rows').innerHTML=list.map(d=>`<tr><td><strong>${escape(d.name)}</strong><small>${escape(d.deviceClass)} · ${escape(d.bus)}${d.vid?` · VID ${escape(d.vid)} / PID ${escape(d.pid||'?')}`:''}</small><details><summary>Device evidence</summary><p>Device digest: ${escape(d.id)}<br>Service: ${escape(d.service||'Unknown')}<br>Windows status: ${escape(d.windowsStatus||'Unknown')}<br>Error code: ${escape(d.errorCode??'Unknown')}</p></details></td><td>${escape(d.provider||'Unknown provider')}<small>${escape(d.version||'Version unknown')} · ${escape(d.inf||'INF unknown')}</small><small>Signature metadata: ${d.signed===true?'Signed':d.signed===false?'Unsigned':'Unknown'}</small></td><td><span class="badge">${escape(d.architecture||'Unknown')}</span><small>Binary: ${escape(d.kernelBinary||'Not resolved')}</small><small>INF targets: ${escape((Array.isArray(d.packageTargets)?d.packageTargets:[]).join(', ')||'Unknown')}</small></td><td><span class="badge ${d.status==='review'?'warn':''}">${d.status==='review'?'Needs review':'Observed'}</span>${(Array.isArray(d.notes)?d.notes:[]).map(n=>`<small>${escape(n)}</small>`).join('')}</td></tr>`).join('')||'<tr><td colspan="4">No devices match these filters.</td></tr>';$('export').disabled=false;}
function load(value){report=validate(value);render();$('message').textContent=(report.sample?'Sample report loaded; these devices are fictional.':'Local report loaded. No data was uploaded.')+(report.warnings?.length?' '+report.warnings.join(' '):'');}
function fail(error){$('message').textContent=error.message||String(error);}
$('file').addEventListener('change',async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>20*1024*1024)throw Error('Report exceeds the 20 MB limit.');load(JSON.parse(await f.text()));}catch(error){fail(error);}});
$('demo').onclick=async()=>{try{load(await(await fetch('sample.json')).json());}catch(error){fail(Error('Use the local server to load the sample, or open sample.json with Open report.'));}};
$('scan').onclick=async()=>{const button=$('scan');button.disabled=true;$('message').textContent='Reading Windows device and driver metadata…';try{const r=await fetch('/scan',{method:'POST',headers:{'X-DriverLens-Scan':'1'}});const value=await r.json();if(!r.ok)throw Error(value.error+(value.detail?' '+value.detail:''));load(value);}catch(error){const offline=location.protocol==='file:'||/failed to fetch|networkerror/i.test(String(error&&error.message||error));if(offline){if(!await helperConnect())fail(Error('Cannot reach the local helper yet. If it is not running, double-click Start-DriverLens.cmd in this folder — this page connects automatically as soon as it is up.'));}else{fail(Error('Scan failed: '+error.message));}}finally{button.disabled=false;}};
for(const id of ['search','status','architecture','bus'])$(id).addEventListener('input',render);
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({...report,devices:filtered(),filterNote:'Filtered export from DriverLens'},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='driverlens-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
const helperProbe=()=>Promise.any([new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok(true);i.onerror=()=>no();i.src='http://127.0.0.1:8781/ping?t='+Date.now();}),fetch('http://127.0.0.1:8781/ping',{mode:'no-cors',cache:'no-store'}).then(()=>true)]).catch(()=>false);const helperConnect=()=>helperProbe().then(alive=>{if(alive)location.replace('http://127.0.0.1:8781/');return alive;});if(location.protocol==='file:'){$('message').textContent='Waiting for the local helper: if it is not running, double-click Start-DriverLens.cmd in this folder (browser pages cannot start local programs themselves). This page connects automatically as soon as it is up.';setInterval(helperConnect,2000);}else{fetch('/report').then(r=>r.ok?r.json():null).then(v=>{if(v)load(v)}).catch(()=>{});}
