//! DriverLens desktop shell — library entry point.
//!
//! Wires the Task 7 command boundary (ten custom commands, ACL-enforced via
//! an explicit command-permission manifest) to the Task 8 collector
//! integration (injectable runner, fixed spawn arguments, app-owned output,
//! 120 s deadline, generation-matched validation).
//!
//! Test layout:
//! - `tests/ipc_boundary.rs` (integration) drives Tauri's mock runtime
//!   through the REAL invoke path — ACL resolution included — proving that an
//!   allowed main-window command responds, an unknown command name is
//!   rejected, a window without the capability is denied, remote origins are
//!   denied, and forged invoke bodies cannot smuggle a program, arguments or
//!   an output path. Integration tests are used because Windows needs the
//!   comctl32 v6 manifest embedded into test binaries that link Tauri's GUI
//!   machinery (rustc embeds no manifest; `build.rs` adds it for test
//!   targets — see `windows-test.manifest`).
//! - unit tests inside `src/` cover the report contract, the collector
//!   pipeline and the scan lifecycle with injected fakes (no Tauri, no real
//!   inventory).
//!
//! Modules are `pub` so the integration tests can construct the manager with
//! injected fakes; this library ships only inside this application.
//!
//! # E2E feature (`wdio-e2e`)
//!
//! `--features wdio-e2e` builds the native WebDriver E2E binary (see
//! `docs/NATIVE-E2E.md`): it registers the embedded WebDriver server
//! (`tauri-plugin-wdio-webdriver`, an optional dependency) and swaps the
//! production collector runner / native dialogs for scripted fakes
//! (`e2e_harness.rs`). The default and release builds contain none of it —
//! every reference below is `#[cfg]`-gated and the plugin dependency is
//! optional.

pub mod collector;
pub mod commands;
#[cfg(feature = "wdio-e2e")]
pub mod e2e_harness;
pub mod notebook;
pub mod report;
pub mod scan;
#[cfg(test)]
mod test_fakes;

use std::sync::Arc;

use tauri::Manager;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        // The complete set of app commands — exactly ten. Permissions for
        // these names are generated by `build.rs` and granted only to the
        // `main` window in `capabilities/default.json`.
        .invoke_handler(tauri::generate_handler![
            commands::scan_devices,
            commands::get_scan_state,
            commands::cancel_scan,
            commands::open_report,
            commands::export_report,
            commands::export_html_report,
            commands::get_report,
            commands::get_notebook,
            commands::save_device_note,
            commands::clear_notebook
        ])
        .setup(|app| setup_scan_manager(app.handle()));

    // E2E-only embedded WebDriver server (feature `wdio-e2e`): registered
    // ONLY in the feature-gated E2E binary. The production build never
    // compiles the plugin (optional dependency) nor this registration.
    #[cfg(feature = "wdio-e2e")]
    let builder = builder.plugin(tauri_plugin_wdio_webdriver::init());

    let app = builder
        .build(tauri::generate_context!())
        .expect("error while running the DriverLens desktop application");

    app.run(|app_handle, event| {
        // On application exit, kill the owned collector child (if any) so
        // closing the app never orphans a scan. Best-effort and non-blocking.
        if let tauri::RunEvent::Exit = event {
            if let Some(manager) = app_handle.try_state::<scan::ScanManager>() {
                manager.shutdown();
            }
        }
    });
}

/// Builds the scan manager once the app handle exists: the private
/// app-owned scans directory lives under the app local data dir (outside the
/// repository and outside OneDrive-synced folders), the collector script is
/// the bundled resource, and the native dialogs are the Tauri Rust-API
/// dialogs.
fn setup_scan_manager(app: &tauri::AppHandle) -> Result<(), Box<dyn std::error::Error>> {
    let scans_dir = app.path().app_local_data_dir()?.join("scans");
    // Extension E-01: the notebook store lives beside the scan temp directory,
    // under the app-owned local data dir (never the repository, never
    // OneDrive-synced folders). Local only — nothing is ever uploaded.
    let notebook = std::sync::Arc::new(notebook::NotebookStore::new(
        app.path().app_local_data_dir()?.join("notebook"),
    ));
    let script = app.path().resolve(
        "resources/Collect-DriverLens.ps1",
        tauri::path::BaseDirectory::Resource,
    )?;

    // Default/production wiring: the real collector runner and the native
    // dialogs. Unchanged by the E2E feature below.
    #[cfg(not(feature = "wdio-e2e"))]
    let config = scan::ScanManagerConfig {
        runner: Arc::new(collector::RealRunner::new(script)),
        dialogs: Some(Arc::new(commands::TauriReportDialogs::new(app.clone()))),
        scans_dir,
        deadline: collector::SCAN_DEADLINE,
    };

    // E2E wiring (feature `wdio-e2e`): scripted synthetic collectors and
    // env-configured fake dialogs — no pwsh, no OS dialogs, no real
    // inventory (see src/e2e_harness.rs).
    #[cfg(feature = "wdio-e2e")]
    let config = scan::ScanManagerConfig {
        runner: Arc::new(e2e_harness::ScriptedRunner::new(script)),
        dialogs: Some(Arc::new(e2e_harness::EnvDialogs)),
        scans_dir,
        deadline: e2e_harness::deadline_from_env().unwrap_or(collector::SCAN_DEADLINE),
    };

    let manager = scan::ScanManager::new(config);
    // The accepted-scan recording hook (extension E-01): best-effort, never
    // fails or blocks a scan.
    manager.attach_notebook(notebook.clone());
    app.manage(manager);
    app.manage(notebook);
    Ok(())
}
