//! Build script for the DriverLens desktop shell.
//!
//! Task 7 boundary: registered custom commands in Tauri v2 are callable from
//! every window/webview by default — unless the application generates explicit
//! command permissions through `AppManifest::commands`. Declaring the seven
//! DriverLens commands here makes `tauri-build`
//!
//! 1. autogenerate one `allow-<command>` / `deny-<command>` permission pair
//!    per command under `permissions/autogenerated/` (underscores become
//!    hyphens), and
//! 2. mark the resolved ACL as "app manifest present", which switches Tauri's
//!    invoke path to *deny by default*: a custom command now runs only when a
//!    capability explicitly grants it to the calling window.
//!
//! The allowlist itself lives in `capabilities/default.json`, which grants the
//! seven `allow-...` permissions to the bundled `main` window only. Plugin
//! capabilities (e.g. the dialog plugin) are resolved separately and are NOT
//! part of this boundary.
//!
//! Verified by real IPC tests (see `src/lib.rs`): an allowed main-window
//! command responds; an unknown command is rejected; a window without the
//! capability is denied before the command body runs.

fn main() {
    // This list must stay in exact sync with the commands registered in
    // `src/lib.rs` (`generate_handler!`). A typo here generates a permission
    // that never matches a command; the matching capability entry would then
    // fail validation at build time.
    let attributes = tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "scan_devices",
            "get_scan_state",
            "cancel_scan",
            "open_report",
            "export_report",
            "export_html_report",
            "get_report",
        ]),
    );
    tauri_build::try_build(attributes).expect("failed to run tauri-build");

    // Test binaries link Windows GUI code through the Tauri shell machinery
    // (menus / native dialogs). That code imports `TaskDialogIndirect` from
    // comctl32, which only resolves through the comctl32 v6 side-by-side
    // assembly declared in an application manifest. tauri-build embeds a
    // manifest into the shipped application binary; rustc embeds none into
    // test binaries, so without this a freshly linked `cargo test` binary
    // fails at load with STATUS_ENTRYPOINT_NOT_FOUND (0xc0000139).
    //
    // Embed the dependency manifest into test targets only: production
    // binaries keep the manifest tauri-build generates.
    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let target_env = std::env::var("CARGO_CFG_TARGET_ENV").unwrap_or_default();
    if target_os == "windows" && target_env == "msvc" {
        let manifest_dir =
            std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR must be set");
        let manifest = std::path::Path::new(&manifest_dir).join("windows-test.manifest");
        println!("cargo:rerun-if-changed={}", manifest.display());
        println!("cargo:rustc-link-arg-tests=/MANIFEST:EMBED");
        println!(
            "cargo:rustc-link-arg-tests=/MANIFESTINPUT:{}",
            manifest.display()
        );
    }
}
